[2024-10-10T15:50:59.678+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-10T15:50:59.695+0900] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 1_handwriting_dag.process_new_data manual__2024-10-10T06:44:07.946117+00:00 [queued]>
[2024-10-10T15:50:59.703+0900] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 1_handwriting_dag.process_new_data manual__2024-10-10T06:44:07.946117+00:00 [queued]>
[2024-10-10T15:50:59.703+0900] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-10T15:50:59.716+0900] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): process_new_data> on 2024-10-10 06:44:07.946117+00:00
[2024-10-10T15:50:59.733+0900] {standard_task_runner.py:72} INFO - Started process 56863 to run task
[2024-10-10T15:50:59.745+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', '1_handwriting_dag', 'process_new_data', 'manual__2024-10-10T06:44:07.946117+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/var/folders/tx/bcbxk5bj33x4r2rt041m7bmr0000gn/T/tmpu60k2fgv']
[2024-10-10T15:50:59.748+0900] {standard_task_runner.py:105} INFO - Job 8: Subtask process_new_data
[2024-10-10T15:50:59.803+0900] {task_command.py:467} INFO - Running <TaskInstance: 1_handwriting_dag.process_new_data manual__2024-10-10T06:44:07.946117+00:00 [running]> on host hyowon-kim-macbook-pro.local
[2024-10-10T15:50:59.873+0900] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='1_handwriting_dag' AIRFLOW_CTX_TASK_ID='process_new_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-10T06:44:07.946117+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-10T06:44:07.946117+00:00'
[2024-10-10T15:50:59.876+0900] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-10T15:50:59.876+0900] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-10T15:50:59.877+0900] {logging_mixin.py:190} INFO - Current task name:process_new_data state:running start_date:2024-10-10 06:50:59.695460+00:00
[2024-10-10T15:50:59.878+0900] {logging_mixin.py:190} INFO - Dag name:1_handwriting_dag and current dag run status:running
[2024-10-10T15:50:59.878+0900] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-10T15:50:59.981+0900] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/alookso/1010LMpj/ml-project-ml-pjt-7/dags/model_dag.py", line 49, in process_new_data
    image = preprocess_canvas_images(image_path)
  File "/Users/alookso/1010LMpj/ml-project-ml-pjt-7/data_processing.py", line 30, in preprocess_canvas_images
    decoded = base64.b64decode(encoded)
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
[2024-10-10T15:50:59.997+0900] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-10T15:50:59.998+0900] {logging_mixin.py:190} INFO - Task start:2024-10-10 06:50:59.695460+00:00 end:2024-10-10 06:50:59.996430+00:00 duration:0.30097
[2024-10-10T15:50:59.999+0900] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_new_data> dag:<DAG: 1_handwriting_dag> dagrun:<DagRun 1_handwriting_dag @ 2024-10-10 06:44:07.946117+00:00: manual__2024-10-10T06:44:07.946117+00:00, state:running, queued_at: 2024-10-10 06:44:07.963351+00:00. externally triggered: True>
[2024-10-10T15:50:59.999+0900] {logging_mixin.py:190} INFO - Failure caused by Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
[2024-10-10T15:51:00.001+0900] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=1_handwriting_dag, task_id=process_new_data, run_id=manual__2024-10-10T06:44:07.946117+00:00, execution_date=20241010T064407, start_date=20241010T065059, end_date=20241010T065059
[2024-10-10T15:51:00.017+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-10T15:51:00.018+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task process_new_data (Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4; 56863)
Traceback (most recent call last):
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/alookso/1010LMpj/ml-project-ml-pjt-7/dags/model_dag.py", line 49, in process_new_data
    image = preprocess_canvas_images(image_path)
  File "/Users/alookso/1010LMpj/ml-project-ml-pjt-7/data_processing.py", line 30, in preprocess_canvas_images
    decoded = base64.b64decode(encoded)
  File "/usr/local/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (1) cannot be 1 more than a multiple of 4
[2024-10-10T15:51:00.056+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-10T15:51:00.074+0900] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-10T15:51:00.074+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
