[2024-10-08T18:40:16.956+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T18:40:16.968+0900] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mnist_model_workflow_2.new_data_sensor manual__2024-10-08T09:34:55.109466+00:00 [queued]>
[2024-10-08T18:40:16.975+0900] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mnist_model_workflow_2.new_data_sensor manual__2024-10-08T09:34:55.109466+00:00 [queued]>
[2024-10-08T18:40:16.975+0900] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-08T18:40:16.988+0900] {taskinstance.py:2888} INFO - Executing <Task(FileSensor): new_data_sensor> on 2024-10-08 09:34:55.109466+00:00
[2024-10-08T18:40:17.003+0900] {standard_task_runner.py:72} INFO - Started process 29030 to run task
[2024-10-08T18:40:17.016+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'mnist_model_workflow_2', 'new_data_sensor', 'manual__2024-10-08T09:34:55.109466+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/mnist_model_dag22.py', '--cfg-path', '/var/folders/tx/bcbxk5bj33x4r2rt041m7bmr0000gn/T/tmp_3msdgps']
[2024-10-08T18:40:17.018+0900] {standard_task_runner.py:105} INFO - Job 26: Subtask new_data_sensor
[2024-10-08T18:40:17.078+0900] {task_command.py:467} INFO - Running <TaskInstance: mnist_model_workflow_2.new_data_sensor manual__2024-10-08T09:34:55.109466+00:00 [running]> on host hyowon-kim-macbook-pro.local
[2024-10-08T18:40:17.144+0900] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mnist_model_workflow_2' AIRFLOW_CTX_TASK_ID='new_data_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T09:34:55.109466+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T09:34:55.109466+00:00'
[2024-10-08T18:40:17.146+0900] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-08T18:40:17.147+0900] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-08T18:40:17.148+0900] {logging_mixin.py:190} INFO - Current task name:new_data_sensor state:running start_date:2024-10-08 09:40:16.969248+00:00
[2024-10-08T18:40:17.148+0900] {logging_mixin.py:190} INFO - Dag name:mnist_model_workflow_2 and current dag run status:running
[2024-10-08T18:40:17.149+0900] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T18:40:17.149+0900] {baseoperator.py:405} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-10-08T18:40:17.156+0900] {base.py:84} INFO - Retrieving connection 'fs_default'
[2024-10-08T18:40:17.157+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.png}
[2024-10-08T18:41:17.161+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.png}
[2024-10-08T18:42:17.176+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.png}
[2024-10-08T18:43:17.182+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.png}
[2024-10-08T18:44:17.185+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.png}
[2024-10-08T18:45:17.188+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.png}
[2024-10-08T18:45:17.190+0900] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 300.0153517140134 seconds exceeds the specified timeout of 300.0.
[2024-10-08T18:45:17.196+0900] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-08T18:45:17.197+0900] {logging_mixin.py:190} INFO - Task start:2024-10-08 09:40:16.969248+00:00 end:2024-10-08 09:45:17.196073+00:00 duration:300.226825
[2024-10-08T18:45:17.197+0900] {logging_mixin.py:190} INFO - Task:<Task(FileSensor): new_data_sensor> dag:<DAG: mnist_model_workflow_2> dagrun:<DagRun mnist_model_workflow_2 @ 2024-10-08 09:34:55.109466+00:00: manual__2024-10-08T09:34:55.109466+00:00, state:running, queued_at: 2024-10-08 09:34:55.125610+00:00. externally triggered: True>
[2024-10-08T18:45:17.198+0900] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 300.0153517140134 seconds exceeds the specified timeout of 300.0.
[2024-10-08T18:45:17.199+0900] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=mnist_model_workflow_2, task_id=new_data_sensor, run_id=manual__2024-10-08T09:34:55.109466+00:00, execution_date=20241008T093455, start_date=20241008T094016, end_date=20241008T094517
[2024-10-08T18:45:17.209+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T18:45:17.209+0900] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task new_data_sensor (Sensor has timed out; run duration of 300.0153517140134 seconds exceeds the specified timeout of 300.0.; 29030)
Traceback (most recent call last):
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 300.0153517140134 seconds exceeds the specified timeout of 300.0.
[2024-10-08T18:45:17.232+0900] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-08T18:45:17.245+0900] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-10-08T18:45:17.258+0900] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T18:45:17.262+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
